/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateFolderDto
 */
export interface CreateFolderDto {

    /**
     * @type {string}
     * @memberof CreateFolderDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateFolderDto
     */
    parentFolderId: string;
}
