/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface FileUserPermission
 */
export interface FileUserPermission {

    /**
     * @type {User}
     * @memberof FileUserPermission
     */
    user: User;

    /**
     * @type {string}
     * @memberof FileUserPermission
     */
    permission: FileUserPermissionPermissionEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum FileUserPermissionPermissionEnum {
    Read = 'read',
    Write = 'write'
}

