/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface FolderUserPermission
 */
export interface FolderUserPermission {

    /**
     * @type {string}
     * @memberof FolderUserPermission
     */
    userId: string;

    /**
     * @type {User}
     * @memberof FolderUserPermission
     */
    user: User;

    /**
     * @type {string}
     * @memberof FolderUserPermission
     */
    permission: FolderUserPermissionPermissionEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum FolderUserPermissionPermissionEnum {
    Read = 'read',
    Write = 'write'
}

