/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InvitableUser
 */
export interface InvitableUser {

    /**
     * @type {string}
     * @memberof InvitableUser
     */
    id: string;

    /**
     * @type {string}
     * @memberof InvitableUser
     */
    givenName: string;

    /**
     * @type {string}
     * @memberof InvitableUser
     */
    name: string;

    /**
     * @type {any}
     * @memberof InvitableUser
     */
    picture: any;
}
