/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Folder } from './folder';
 /**
 * 
 *
 * @export
 * @interface ModelFile
 */
export interface ModelFile {

    /**
     * @type {string}
     * @memberof ModelFile
     */
    id: string;

    /**
     * @type {string}
     * @memberof ModelFile
     */
    name: string;

    /**
     * @type {Date}
     * @memberof ModelFile
     */
    createdAt: Date;

    /**
     * @type {number}
     * @memberof ModelFile
     */
    size: number;

    /**
     * @type {string}
     * @memberof ModelFile
     */
    mimeType: string;

    /**
     * @type {Folder}
     * @memberof ModelFile
     */
    folder: Folder;
}
