/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserFilePermissionInput
 */
export interface UpdateUserFilePermissionInput {

    /**
     * @type {string}
     * @memberof UpdateUserFilePermissionInput
     */
    permission: UpdateUserFilePermissionInputPermissionEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateUserFilePermissionInputPermissionEnum {
    Read = 'read',
    Write = 'write'
}

