/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FolderUserPermission } from './folder-user-permission';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    id: string;

    /**
     * @type {string}
     * @memberof User
     */
    name: string;

    /**
     * @type {string}
     * @memberof User
     */
    picture: string;

    /**
     * @type {Array<FolderUserPermission>}
     * @memberof User
     */
    sharedPermission: Array<FolderUserPermission>;
}
